---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-floating-ip-operator
  namespace: kube-system
  labels:
    app: floating-ip-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floating-ip-operator
  template:
    metadata:
      labels:
        app: floating-ip-operator
    spec:
      serviceAccount: hcloud-floating-ip-operator
      containers:
      - name: operator
        image: zenjoy/hcloud-floating-ip-operator:latest
        env:
        - name: HCLOUD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: hcloud
              key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
type: Opaque
data:
  token: HERE-YOUR-TOKEN