apiVersion: hcloud.zenjoy.be/v1alpha1
kind: FloatingIPPool
metadata:
  name: load-balancer-worker-pool
spec:
  ips: 
  - 78.46.244.114
  - 78.46.244.115
  intervalSeconds: 60
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
