---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-floating-ip-operator
rules:
- apiGroups:
    - ""
  resources: 
    - nodes
  verbs: 
    - get
    - watch
    - list
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - watch
    - list
    - create
    - update
    - patch
    - delete
- apiGroups: ["hcloud.zenjoy.be"]
  resources:
    - floatingippools
  verbs:
    - get
    - watch
    - list
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hcloud-floating-ip-operator
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hcloud-floating-ip-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hcloud-floating-ip-operator
subjects:
  - kind: ServiceAccount
    name: hcloud-floating-ip-operator
    namespace: kube-system