[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "github.com/hetznercloud/hcloud-go"
  version = "v1.7.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "github.com/spotahome/kooper"
  version = "v0.5.0"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"